repos:
- repo: https://github.com/asottile/pyupgrade
  rev: v1.15.0
  hooks:
  - id: pyupgrade
    args: ["--py3-plus"]
- repo: https://github.com/asottile/add-trailing-comma
  rev: v0.8.0
  hooks:
  - id: add-trailing-comma
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v2.1.0
  hooks:
  - id: trailing-whitespace
  - id: double-quote-string-fixer
  - id: end-of-file-fixer
- repo: https://gitlab.com/pycqa/flake8
  rev: 3.7.7
  hooks:
  - id: flake8
