# Config file for automatic testing at travis-ci.org

language: python
# http://blog.travis-ci.com/2014-12-17-faster-builds-with-container-based-infrastructure/
sudo: false
python:
  - "3.5"
  - "3.4"
  - "3.3"
  - "2.7"
  - "2.6"
  - "pypy"

before_install:
  - pip install -U pip

install:
  - pip install -U .[reco]
  - pip install -U -r dev-requirements.txt

before_script:
  - flake8 .

script: python setup.py test
